### ISSUE TITLE
Load top category product

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/Shopping-Android#22]
Đôi khi không hiển thị top categrory product khi mở ứng dụng @nguyenht65

**Comment by nguyenht65** [comment]
Do nó lag đấy 🥲

**Comment by nguyenht65** [comment]
> Đôi khi không hiển thị top categrory product khi mở ứng dụng @nguyenht65 

Liệu có phải do lag không nhỉ? Tôi chạy lên ầm ầm mà @@

**Comment by FPT-NMTung** [comment]
> > Đôi khi không hiển thị top categrory product khi mở ứng dụng @nguyenht65
> 
> Liệu có phải do lag không nhỉ? Tôi chạy lên ầm ầm mà @@

T không thấy nó gọi lên server nữa, ô kiểm tra lại xem nhé

**Comment by nguyenht65** [comment]
tôi chỉ bị mạng lag xong nó call rồi trả data lâu hơn thôi thôi. chứ nếu mạng k lag thì của tôi chạy bình thường @@
ấn đi ấn lại qua tất cả các tab luôn r ấy
