### ISSUE TITLE
Sai title email + làm rõ ship fee

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/Shopping-Android#24]
sửa lại title email , hiện tại phí ship đang để là "fee" -> chưa rõ ràng

**Comment by DUONGMON2000** [comment]
Thêm địa chỉ , tên , sđt người đặt hàng vào confirm email

**Comment by FPT-NMTung** [comment]
Đã thêm
![image](https://user-images.githubusercontent.com/63092029/158030940-50b82d51-c26e-423e-9833-806752a1b72e.png)
