### ISSUE TITLE
Sửa lại bố cục , xuống dòng phần thank you sau check out

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/Shopping-Android#33]
![image](https://user-images.githubusercontent.com/86470329/158549392-0a7b5c32-372a-42af-8eca-90d6dc9c2a47.png)

**Comment by FPT-NMTung** [comment]
![image](https://user-images.githubusercontent.com/63092029/158578994-cc4b2bad-1f25-440e-922e-7780ca4e42b4.png)
