### ISSUE TITLE
Chưa hiển thị full danh sách yêu thích

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/Shopping-Android#34]
![image](https://user-images.githubusercontent.com/86470329/158551193-2f21edb8-5f6c-43f7-b8b5-ad2e2643b57e.png)

**Comment by nguyenht65** [comment]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/64007926/158554972-6b47d8e9-22a6-4019-b307-6eb4187c0012.png">
fixed
