### ISSUE TITLE
check permission truy cập thư viện ảnh

### ISSUE THREAD

**Issue by nguyenht65** [FPT-NMTung/Shopping-Android#37]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/64007926/158572369-1012a4dd-fca1-48e8-a1c5-ae8ea65fb97b.png">

**Comment by nguyenht65** [comment]
if (checkSelfPermission(Manifest.permission.WRITE_CONTACTS) != PackageManager.PERMISSION_GRANTED) {
            requestPermissions(new String[]{Manifest.permission.WRITE_CONTACTS}, 101);
        }
ví dụ câu lệnh check permission

**Comment by abcmonboi** [comment]
https://user-images.githubusercontent.com/95062907/158579889-cbedda0a-1409-49b3-a522-63e167d22f5b.png
